### ISSUE TITLE
Angular: Create and Edit Product

### ISSUE THREAD

**Issue by muradhajiyev** [muradhajiyev/cs572-ecommerce-project#73]
As a seller, on the menu part, there are 2 options: His products and orders.
when the products section is clicked, the products list will be shown.
On top of product list, create a product button will be located.
and on each product, edit button will be located.

Only create and edit product functionality should be implemented.

A simple product form: title, price, description, image, etc.

**Comment by AminPlusPlus** [comment]
- [ ] 

1.
